name: splash_ifmt
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

vars:
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner
scripts:
  mobx_build: $runner build
  mobx_watch: $clean & $get & $runner watch
  mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  flutter_modular: ^5.0.3
  flutter_screenutil: ^5.0.0+2
  google_sign_in: ^5.2.1
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  retrofit_generator: 
  responsive_framework: ^0.1.4
  syncfusion_flutter_core: ^20.2.40
  syncfusion_flutter_sliders: ^20.2.40
  carousel_slider: ^4.0.0
  device_preview: ^1.0.0
  flutter_slidable: ^1.2.0
  font_awesome_flutter: ^10.1.0
  flutter_svg: ^1.0.3
  retrofit: ^3.0.1
  json_annotation: ^4.0.1
  json_serializable: ^6.1.4
  connectivity: ^3.0.6
  dio: ^4.0.0
  flutter_mobx: ^2.0.0
  mobx: ^2.0.1
  bot_toast: ^4.0.1
  shared_preferences: ^2.0.8
  url_launcher: ^6.0.12
  mask_text_input_formatter: ^2.0.0
  flutter_google_places: ^0.3.0
  cupertino_date_textbox: ^1.0.1
  flutter_holo_date_picker: ^1.0.1+2
  analyzer: ^3.2.0
  water_drop_nav_bar:
  syncfusion_flutter_datagrid: ^20.2.40
  mqtt_client: 

dependency_overrides:
  analyzer:

dev_dependencies:
  hive_generator: ^1.1.0
  modular_codegen: ^3.0.0
  mobx_codegen: ^2.0.1+3
  build_runner:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
