// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5qGtECYfP7h4rNweI5SuLGLqgE-6MlHM',
    appId: '1:155595857432:web:d4a9c058d13ba0c402ed6d',
    messagingSenderId: '155595857432',
    projectId: 'ar-ernany',
    authDomain: 'ar-ernany.firebaseapp.com',
    storageBucket: 'ar-ernany.appspot.com',
    measurementId: 'G-YJDV5412GN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJDwMnUji0RJLUy-g3gyEZTxggjUSR1G0',
    appId: '1:155595857432:android:fbee06efd67b660a02ed6d',
    messagingSenderId: '155595857432',
    projectId: 'ar-ernany',
    storageBucket: 'ar-ernany.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO1F9DAQ6G_glqicfv8KgH28qT0V4cslY',
    appId: '1:155595857432:ios:dbea4b6e1051993402ed6d',
    messagingSenderId: '155595857432',
    projectId: 'ar-ernany',
    storageBucket: 'ar-ernany.appspot.com',
    iosClientId: '155595857432-ce53khnona3ci491ecddnun7rotsclsj.apps.googleusercontent.com',
    iosBundleId: 'com.example.splashIfmt',
  );
}
